version: '3'

services:
  postgresql:
    build:
      context: ./app/db
      dockerfile: Dockerfile
    ports:
      - '5433:5432'
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@postgres'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    ports:
      - '16543:80'
    depends_on:
      - postgresql
