version: '3'

services:
  app:
    build: . #
    container_name: api
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgresql:5432/match_job_developer_dev
    volumes:
      - .:/usr/app
